SQL> /
PACKAGE      b2w_api_cliente IS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  --                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  -- +===========================================================================================+                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |    Copyright (c) 2008 MJV Informática, Rio de Janeiro, Brasil                             |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |                       All rights reserved.                                                |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- +===========================================================================================+                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- | FILENAME                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |   B2W_API_CLIENTE                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                
  -- |                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- | PURPOSE                                                                                   |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |    Criar, alterar, e inativar clientes e endereços.                                                                |                                                                                                                                                                                                                                                                                                                                                                                         
  -- |                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- | PARAMETERS                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |    p_endereco           : Estrutura de endereço                                            |                                                                                                                                                                                                                                                                                                                                                                                                                 
  -- |    p_cliente           : Estrutura de cliente                                            |                                                                                                                                                                                                                                                                                                                                                                                                                   
  -- |                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- | CREATED BY                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |   MARCOS COSTA           (JUNHO/2008)     GAP 374                                         |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- | ALTERED BY                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |      FERNANDO SISNEIRO  ( JULHO, AGOSTO / 2008)  - REFEITO AS PROCEDURES                  |                                                                                                                                                                                                                                                                                                                                                                                                                  
  -- |      ALTAIR COSTA       (JULHO, AGOSTO /2008)                                                   |                                                                                                                                                                                                                                                                                                                                                                                                            
  -- +===========================================================================================+                                                                                                                                                                                                                                                                                                                                                                                                                  
  /*   ##########                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
      PROCEDURE b2w_insere_endereco_sac (                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        x_desc_erro    OUT      VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        x_cod_erro     OUT      VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        p_id_cliente   IN       VARCHAR2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        p_endereco     IN       B2WCUSTOMER.address_tbl,                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        p_usuario      IN       VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
           );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  PROCEDURE b2w_insere_endereco                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    x_desc_erro OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,x_cod_erro  OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,p_endereco  IN b2wcustomer.address_tbl                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
   ,p_usuario   IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  PROCEDURE b2w_altera_cliente                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    x_desc_erro OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,x_cod_erro  OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,p_cliente   IN b2wcustomer.customer_tbl                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   ,p_usuario   IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  PROCEDURE b2w_inativa_endereco                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    x_desc_erro OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,x_cod_erro  OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,id_cliente  IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   ,id_endereco IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   ,p_usuario   IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  PROCEDURE b2w_insere_cliente                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    x_desc_erro OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,x_cod_erro  OUT VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   ,pa_cliente  IN b2wcustomer.customer_tbl                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
   ,p_usuario   IN VARCHAR2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
END b2w_api_cliente;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
SQL> spool off
