--
PROMPT 
PROMPT Corrige Transacoes SIASIS
PROMPT
--
set serverout ON;
DECLARE
V_TRANSACTION_TYPE_ID NUMBER;
V_TRANSACTION_INTERFACE_ID NUMBER;
V_COUNT NUMBER :=0;
BEGIN
FOR REG IN(
SELECT 
 ORGANIZATION_ID
 ,INVENTORY_ITEM_ID
 ,SOURCE_LINE_ID
 ,SUBINVENTORY_CODE
 ,COUNT(*) QT
FROM APPS.MTL_MATERIAL_TRANSACTIONS
WHERE TRANSACTION_DATE > = TO_DATE('01082013', 'DDMMRRRR')
 AND TRANSACTION_DATE < TO_DATE('01102013', 'DDMMRRRR')
 AND SOURCE_CODE ='INTERFACE-SIA-INV' 
 AND ORGANIZATION_ID IN (134,133,136,137,138,139,140,141,142,321,325,320,318,322,324,323,319,317,135,431)
 AND TRANSACTION_TYPE_ID IN (213,176,214)
GROUP BY
 ORGANIZATION_ID
 ,INVENTORY_ITEM_ID
 ,SOURCE_LINE_ID
 ,SUBINVENTORY_CODE
HAVING COUNT(*) > 1) LOOP
--IF REG.SOURCE_LINE_ID not IN (11431857,11434931,11430927,11490533,11435263) THEN
 FOR REG1 IN (
  SELECT *
  FROM APPS.MTL_MATERIAL_TRANSACTIONS
  WHERE ORGANIZATION_ID = REG.ORGANIZATION_ID
  AND INVENTORY_ITEM_ID = REG.INVENTORY_ITEM_ID
  AND SOURCE_LINE_ID =  REG.SOURCE_LINE_ID
  AND TRANSACTION_DATE > = TO_DATE('01082013', 'DDMMRRRR')
  AND SUBINVENTORY_CODE = REG.SUBINVENTORY_CODE
  AND  ROWNUM < REG.QT) LOOP 
  
  IF REG1.TRANSACTION_TYPE_ID = 200 THEN
     V_TRANSACTION_TYPE_ID := 209;
  ELSIF REG1.TRANSACTION_TYPE_ID = 213 THEN
     V_TRANSACTION_TYPE_ID := 204;
  ELSIF REG1.TRANSACTION_TYPE_ID = 214 THEN
     V_TRANSACTION_TYPE_ID := 206;  
  ELSIF REG1.TRANSACTION_TYPE_ID = 210 THEN
     V_TRANSACTION_TYPE_ID := 464;
  ELSIF REG1.TRANSACTION_TYPE_ID = 176 THEN
     V_TRANSACTION_TYPE_ID := 205;
  ELSIF REG1.TRANSACTION_TYPE_ID = 206 THEN
     V_TRANSACTION_TYPE_ID := 214;  
  ELSIF REG1.TRANSACTION_TYPE_ID = 205 THEN
     V_TRANSACTION_TYPE_ID := 176;
  ELSIF REG1.TRANSACTION_TYPE_ID = 283 THEN
     V_TRANSACTION_TYPE_ID := 260; 
  ELSIF REG1.TRANSACTION_TYPE_ID = 204 THEN
     V_TRANSACTION_TYPE_ID := 213;
  END IF;                             
--
  SELECT APPS.MTL_MATERIAL_TRANSACTIONS_S.NEXTVAL
       INTO V_TRANSACTION_INTERFACE_ID
       FROM DUAL;
--
       INSERT INTO APPS.MTL_TRANSACTIONS_INTERFACE
        (TRANSACTION_INTERFACE_ID
        ,SOURCE_CODE
        ,SOURCE_LINE_ID
        ,SOURCE_HEADER_ID
        ,PROCESS_FLAG
        ,TRANSACTION_MODE
        ,LOCK_FLAG
        ,INVENTORY_ITEM_ID
        ,ORGANIZATION_ID
        ,TRANSACTION_QUANTITY
        ,PRIMARY_QUANTITY
        ,TRANSACTION_UOM
        ,TRANSACTION_DATE
        ,SUBINVENTORY_CODE
        ,TRANSACTION_TYPE_ID
        ,TRANSACTION_REFERENCE
        ,DISTRIBUTION_ACCOUNT_ID
        ,LAST_UPDATE_DATE
        ,LAST_UPDATED_BY
        ,CREATION_DATE
        ,CREATED_BY 
        ,ATTRIBUTE1
        ,ATTRIBUTE2
        ,ATTRIBUTE3
        ,ATTRIBUTE4
        ,ATTRIBUTE5
        ,ATTRIBUTE6
        ,ATTRIBUTE7
        ,ATTRIBUTE8
        ,ATTRIBUTE9
        ,ATTRIBUTE10
        ,ATTRIBUTE11
        ,ATTRIBUTE12
        ,ATTRIBUTE13
        ,ATTRIBUTE14
        ,ATTRIBUTE15
         )
       VALUES
        (V_TRANSACTION_INTERFACE_ID
        ,'INTERFACE-SIA-INV'     --SOURCE_CODE
        ,REG1.SOURCE_LINE_ID
        ,V_TRANSACTION_INTERFACE_ID
        ,1                       --PROCESS_FLAG
        ,3                       --TRANSACTION_MODE
        ,2                       --LOCK_FLAG
        ,REG1.INVENTORY_ITEM_ID   --INVENTORY_ITEM_ID
        ,REG1.ORGANIZATION_ID     --ORGANIZATION_ID
        ,REG1.TRANSACTION_QUANTITY * -1            --TRANSACTION_QUANTITY
        ,REG1.TRANSACTION_QUANTITY * -1           --PRIMARY_QUANTITY
        ,REG1.TRANSACTION_UOM   --TRANSACTION_UOM
        ,SYSDATE                 --TRANSACTION_DATE
        ,REG1.SUBINVENTORY_CODE   --SUBINVENTORY_CODE
        ,V_TRANSACTION_TYPE_ID --TRANSACTION_TYPE_ID
        ,'ESTORNO ' || REG1.TRANSACTION_REFERENCE   --TRANSACTION_REFERENCE
        ,REG1.DISTRIBUTION_ACCOUNT_ID
        ,SYSDATE                 --LAST_UPDATE_DATE
        ,FND_GLOBAL.USER_ID      --LAST_UPDATED_BY
        ,SYSDATE                 --CREATION_DATE
        ,FND_GLOBAL.USER_ID      --CREATED_BY 
        ,REG1.ATTRIBUTE1
        ,REG1.ATTRIBUTE2
        ,REG1.ATTRIBUTE3
        ,REG1.ATTRIBUTE4
        ,REG1.ATTRIBUTE5
        ,REG1.ATTRIBUTE6
        ,REG1.ATTRIBUTE7
        ,REG1.ATTRIBUTE8
        ,REG1.ATTRIBUTE9
        ,REG1.ATTRIBUTE10
        ,REG1.ATTRIBUTE11
        ,REG1.ATTRIBUTE12
        ,REG1.ATTRIBUTE13
        ,REG1.ATTRIBUTE14
        ,REG1.ATTRIBUTE15 
        ); 
        V_COUNT := V_COUNT +1;
   FOR REG2 IN (
    SELECT * FROM INV.MTL_TRANSACTION_LOT_NUMBERS
    WHERE TRANSACTION_ID = REG1.TRANSACTION_ID) LOOP
--    
    INSERT INTO MTL_TRANSACTION_LOTS_INTERFACE
           (TRANSACTION_INTERFACE_ID
           ,SOURCE_CODE
           ,SOURCE_LINE_ID
           ,LAST_UPDATE_DATE
           ,LAST_UPDATED_BY
           ,CREATION_DATE
           ,CREATED_BY
           ,LOT_NUMBER
           ,TRANSACTION_QUANTITY
           ,PRIMARY_QUANTITY)
          VALUES
           (V_TRANSACTION_INTERFACE_ID
           ,'INTERFACE-SIA-INV'
           ,V_TRANSACTION_INTERFACE_ID
           ,SYSDATE
           ,FND_GLOBAL.USER_ID
           ,SYSDATE
           ,FND_GLOBAL.USER_ID
           ,REG2.LOT_NUMBER
           ,REG2.TRANSACTION_QUANTITY -1
           ,REG2.PRIMARY_QUANTITY -1 );     
 END LOOP;
 END LOOP;
--END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE ('No.of rows Updated of PAC = '|| V_COUNT);
COMMIT;  
EXCEPTION 
WHEN OTHERS THEN 
 ROLLBACK;
 DBMS_OUTPUT.PUT_LINE(' Error message: ' || SQLERRM );
END;
/
