SELECT LH.INST_ID LOCKING_INST, LH.SID LOCKING_SID,
LW.INST_ID WAITING_INST, LW.SID WAITER_SID,
DECODE ( LH.TYPE, 'MR', 'MEDIA_RECOVERY',
'RT', 'REDO_THREAD',
'UN', 'USER_NAME',
'TX', 'TRANSACTION',
'TM', 'DML',
'UL', 'PLSQL USER_LOCK',
'DX', 'DISTRTED_TRANSAXION',
'CF', 'CONTROL_FILE',
'IS', 'INSTANCE_STATE',
'FS', 'FILE_SET',
'IR', 'INSTANCE_RECOVERY',
'ST', 'DISKSPACE TRANSACTION',
'IV', 'LIBCACHE_INVALIDATION',
'LS', 'LOGSTAARTORSWITCH',
'RW', 'ROW_WAIT',
'SQ', 'SEQUENCE_NO',
'TE', 'EXTEND_TABLE',
'TT', 'TEMP_TABLE',
'NOTHING-' ) WAITER_LOCK_TYPE,
DECODE ( LW.REQUEST, 0, 'NONE',
1, 'NOLOCK',
2, 'ROW-SHARE',
3, 'ROW-EXCLUSIVE',
4, 'SHARE-TABLE',
5, 'SHARE-ROW-EXCLUSIVE',
6, 'EXCLUSIVE',
'NOTHING-' ) WAITER_MODE_REQ
FROM GV$LOCK LW, GV$LOCK LH
WHERE LH.ID1=LW.ID1
AND LH.ID2=LW.ID2
AND LH.REQUEST=0
AND LW.LMODE=0
AND (LH.ID1,LH.ID2) IN (
SELECT ID1,ID2 FROM GV$LOCK WHERE REQUEST=0
INTERSECT
SELECT ID1,ID2 FROM GV$LOCK WHERE LMODE=0 );
