col username for a8
col machine for a30
select * from ( SELECT SES.SID, SES.SERIAL# SERIAL, SES.USERNAME, SUBSTR(SES.MACHINE, 1, 20) MACHINE, SUBSTR(SES.PROGRAM, 1, 20) PROGRAM, T.NAME,
          FLOOR(S.VALUE/1024/1024) "TOTAL(MB)", to_char(ses.sql_hash_value) hashvalue, ses.module
   FROM V$SESSTAT S, V$STATNAME T, V$SESSION SES
  WHERE S.STATISTIC# = T.STATISTIC# AND UPPER(T.NAME) LIKE '%SESSION%PGA MEMORY' AND S.SID = SES.SID and FLOOR(S.VALUE/1024/1024) > 500
  ORDER BY 7 desc, 4, 1, 5) where rownum < 50
/
select
           FLOOR(sum(S.VALUE)/1024/1024) "TOTAL(MB)"
     FROM V$SESSTAT S, V$STATNAME T, V$SESSION SES
  WHERE S.STATISTIC# = T.STATISTIC# AND UPPER(T.NAME) LIKE '%SESSION%PGA MEMORY' AND S.SID = SES.SID
/

