SET pagesize 20
SET lines 1000
COL "PATCH" format a16
COL "LANG" format a4
COL "Env" format a6
COL "Inicio" format a19
COL "Termino" format a19
COL "OK?" format a5
COL DRIVER_FILE_NAME format a20
select distinct
	D.PATCH_NAME as "PATCH",
	L.LANGUAGE as "LANG",
	C.DRIVER_FILE_NAME,
	TO_CHAR(A.START_DATE, 'DD/MM/YY HH24:MI:SS') as "Inicio",
	TO_CHAR(A.END_DATE, 'DD/MM/YY HH24:MI:SS') as "Termino",
	A.SUCCESS_FLAG as "OK?",
	B.APPLICATIONS_SYSTEM_NAME AS "Env"
from
	AD_PATCH_RUNS A,
	AD_APPL_TOPS B,
	AD_PATCH_DRIVERS C,
	AD_APPLIED_PATCHES D,
	AD_PATCH_DRIVER_LANGS L,
	AD_BUGS G,
	AD_PATCH_RUN_BUGS R
where
	A.APPL_TOP_ID = B.APPL_TOP_ID
	AND A.PATCH_DRIVER_ID = C.PATCH_DRIVER_ID
	AND C.APPLIED_PATCH_ID = D.APPLIED_PATCH_ID
	AND L.PATCH_DRIVER_ID = C.PATCH_DRIVER_ID
	AND A.PATCH_RUN_ID = R.PATCH_RUN_ID
	AND G.BUG_ID = R.BUG_ID
	AND A.PATCH_DRIVER_ID in
	(select
		PATCH_DRIVER_ID
	 from AD_PATCH_DRIVERS
	 where APPLIED_PATCH_ID in
	 (select
	 		APPLIED_PATCH_ID
	 	from
	 	AD_APPLIED_PATCHES
	 	where PATCH_NAME like upper('%&1%')
	 	)
	 	) ORDER BY 1, 4
/
