/*--Verificar Sessoes ativas no banco.*/
set lines 999 
COL USERNAME FOR A20
COL MACHINE FOR A30
COL OBJECT_NAME FOR A20
 SELECT S.SID, S.SERIAL#, S.USERNAME, S.MACHINE, S.SECONDS_IN_WAIT, STATE, 
 STATUS, PROCESS AS "OS PROCESS", WAIT_TIME FROM V$SESSION S ORDER BY S.SECONDS_IN_WAIT;