/*--VERIFICA A VERSÃO DO ORACLE E EM QUAL INSTANCIA ESTAMOS CONECTADOS. */
SET LINES 999
COL HOST FOR A25
SELECT HOST_NAME AS "HOST", INSTANCE_NAME "INSTANCIA",STARTUP_TIME AS "STARTUP", VERSION "VERSION",
SHUTDOWN_PENDING AS "SP", DATABASE_STATUS, INSTANCE_ROLE, ACTIVE_STATE
FROM V$INSTANCE;



